name: OpenOSRS - Scraper

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  scrape-npcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
        with:
          repository: open-osrs/cache-client
          ref: master
          path: cache-client

      - uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: cache-client

      - name: Assembling cache client
        run: ./gradlew assemble --console=plain
        working-directory: cache-client

      - name: Downloading jagex cache
        run: ./gradlew download --console=plain
        working-directory: cache-client

      - uses: actions/checkout@v2.3.2
        with:
          repository: open-osrs/runelite
          ref: master
          path: OpenOSRS

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: OpenOSRS

      - name: Assembling scraper
        run: ./gradlew :wiki-scraper:assemble --console=plain
        working-directory: OpenOSRS

      - name: Building cache client
        run: ./gradlew build --console=plain
        working-directory: cache-client

      - name: Building scraper
        run: ./gradlew :wiki-scraper:build --console=plain
        working-directory: OpenOSRS

      - name: Scraping NPC stats
        run: ./gradlew :wiki-scraper:npcStatsScrape --console=plain
        working-directory: OpenOSRS

      - name: Commit NPC stats
        run: |
          git add $(git ls-files -o --exclude-standard) runelite-client/src/main/resources/npc_stats.json
          git diff-index --quiet HEAD \
          || git -c user.name="OpenOSRS" -c user.email="openosrs.github@gmail.com" commit \
            --author="OpenOSRS <openosrs.github@gmail.com>" \
            -m "Client: Update NPC stats"
        working-directory: OpenOSRS

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.OPENOSRS }}
          directory: /home/runner/work/runelite/runelite/OpenOSRS
          repository: open-osrs/runelite
